### PR TITLE
feat: add Terraform devcontainer

### LINKED ISSUE #44: Create Terraform `devcontainer` for local dev
Include:

* asdf (manage Terraform version)
* Docker
* make

### PR DESCRIPTION
**Pull request by patheard**
Includes asdf, Terraform and AWS CLI with access to host Docker.

Closes #44

### CODE REVIEW

**Review by maxneuvians — APPROVED** [review]
Looks good - you may not end up needing the access to the docker host which would slim it a bit, but at the same time, it can't hurt. Nice work! 🎉

**Comment by maxneuvians** [comment]
Would also recommend merging this into the other environments we have (staging, maybe prod)

**Comment by maxneuvians** [comment]
Also adding terragrunt executable might be a nice addon

**Comment by patheard** [comment]
Yeah, would definitely like to get this in the other environments as well.  

For terragrunt, I added the [asdf plugin](https://github.com/cds-snc/covid-alert-server-demo-terraform/blob/master/.devcontainer/library-scripts/asdf-terraform.sh#L8), so if it's included in a project's `.tool-versions` file, it'll get added automagically by the `asdf install` command.  It might make more sense just to have the install in the Dockerfile though - I need to use the devcontainer more to get a feeling for what it needs 😁

**Pull request merged**
